"""
Django settings for core_project project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
# Asegúrate de importar estas librerías si las usas:
from decouple import config 
from dotenv import load_dotenv 

# ⚠️ CARGA FORZADA DE VARIABLES DE ENTORNO AL INICIO ⚠️
load_dotenv() 

BASE_DIR = Path(__file__).resolve().parent.parent
# -------------------------------------------------------------------
# 1. SEGURIDAD Y HOSTS
# -------------------------------------------------------------------
SECRET_KEY = os.getenv('SECRET_KEY', default='django-insecure-vr^jtl^umh3!=9b*rk)&1erydyyh#!ppu_hji#dcidf)=gfvkv')
DEBUG = os.getenv('DEBUG', 'True') == 'True' # Leer DEBUG de forma segura

# CRÍTICO: El host público de Render sin HTTPS
# core_project/settings.py

# settings.py

# core_project/settings.py

ALLOWED_HOSTS = [
    '127.0.0.1', 
    'localhost',
    'neuropulse-1.onrender.com', 
    # AÑADE ESTO TEMPORALMENTE:
    '.onrender.com'
]
# -------------------------------------------------------------------
# 2. APLICACIONES INSTALADAS (¡CORRECCIÓN DE UBICACIÓN!)
# -------------------------------------------------------------------

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Tu app
    'dashboard', 
]

# -------------------------------------------------------------------
# 3. MIDDLEWARE (WHITENOISE)
# -------------------------------------------------------------------

MIDDLEWARE = [
    # Seguridad y Archivos Estáticos (Whitenoise)
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', 
    
    # Manejo de Sesiones, Cookies y CSRF
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    
    # ⬅️ AQUÍ VA EL ERROR E408
    'django.contrib.auth.middleware.AuthenticationMiddleware', 
    
    # ⬅️ AQUÍ VA EL ERROR E409
    'django.contrib.messages.middleware.MessageMiddleware', 
    
    # Seguridad final
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core_project.urls'

# ... (El resto de la configuración de TEMPLATES y WSGI permanece igual) ...

# -------------------------------------------------------------------
# 4. CONFIGURACIÓN DE BASE DE DATOS
# -------------------------------------------------------------------

# 1. Base de datos por defecto (SQLite para desarrollo local)
# core_project/settings.py

# ... (Importaciones de os, config, etc.) ...

DATABASES = {
    'default': {
        # 1. CRÍTICO: Codifica el valor del ENGINE. Nunca debería ser leído de una variable de entorno.
        'ENGINE': 'django.db.backends.postgresql', 
        
        # 2. El resto de los valores se leen de forma segura del entorno/decouple:
        'NAME': os.getenv("SUPABASE_DBNAME", 'postgres'), # Usar 'postgres' como respaldo seguro
        'USER': os.getenv("SUPABASE_USER", 'postgres'),
        'PASSWORD': os.getenv("SUPABASE_PASSWORD"),
        'HOST': os.getenv("SUPABASE_HOST"),
        'PORT': os.getenv("SUPABASE_PORT", "5432"),
        'OPTIONS': {
            'sslmode': 'require',
        },
    }
}

# 2. Sobrescribir con PostgreSQL (Render/Supabase)
# Render establece la variable de entorno DATABASE_URL automáticamente.
if os.environ.get('DATABASE_URL'):
    DATABASES['default'] = dj_database_url.parse(
        os.environ.get('DATABASE_URL'),
        conn_max_age=600,
        conn_health_check=True,
    )
    
    # CRÍTICO: Forzar el uso de SSL para la conexión remota a Supabase
    DATABASES['default']['OPTIONS'] = {
        'sslmode': 'require',
    }


# -------------------------------------------------------------------
# 5. ARCHIVOS ESTÁTICOS (CRÍTICO PARA RENDER)
# -------------------------------------------------------------------

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'dashboard/static'),
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# core_project/settings.py

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"], # Esto es opcional, pero si lo tienes, está bien.
        'APP_DIRS': True, # ⬅️ ESTO DEBE SER TRUE
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth', # ⬅️ CRÍTICO para auth
                'django.contrib.messages.context_processors.messages', # ⬅️ CRÍTICO para mensajes
            ],
        },
    },
]

