# Generated by Django 5.2.8 on 2025-11-15 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroFisiologico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('valor_gsr', models.IntegerField(verbose_name='Valor GSR (Estrés)')),
                ('valor_bpm', models.IntegerField(verbose_name='Valor BPM (Pulso)')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro Fisiológico',
                'verbose_name_plural': 'Registros Fisiológicos',
                'ordering': ['-timestamp'],
            },
        ),
    ]
