# Generated by Django 4.2.8 on 2025-11-21 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivacionSistema',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('activation', models.BooleanField(db_column='activation', default=False)),
            ],
            options={
                'verbose_name': 'Activación del Sistema',
                'verbose_name_plural': 'Activaciónes del Sistema',
                'db_table': 'activacion_sistema',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='registrofisiologico',
            options={'managed': False, 'ordering': ['-creado_en'], 'verbose_name': 'Registro Fisiológico', 'verbose_name_plural': 'Registros Fisiológicos'},
        ),
    ]
