# Generated by Django 4.2.8 on 2025-11-22 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_activacionsistema_alter_registrofisiologico_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='registrofisiologico',
            table='usuarios',
        ),
    ]
